export enum destinationActionType {
    FETCH_DESTINATION_START = "FETCH_DESTINATION_START",
    FETCH_DESTINATION_SUCCESS = "FETCH_DESTINATION_SUCCESS",
    FETCH_DESTINATION_FAIL = "FETCH_DESTINATION_FAIL",
}