export enum destinationActionType {
    FETCH_DESTINATION_CLEAR = 'FETCH_DESTINATION_CLEAR',
    FETCH_DESTINATION_START = 'FETCH_DESTINATION_START',
    FETCH_DESTINATION_SUCCESS = 'FETCH_DESTINATION_SUCCESS',
    FETCH_DESTINATION_FAIL = 'FETCH_DESTINATION_FAIL'  
}

export enum departureAirportActionType {
    FETCH_DEPARTUREAIRPORT_CLEAR = 'FETCH_DEPARTUREAIRPORT_CLEAR',
    FETCH_DEPARTUREAIRPORT_START = 'FETCH_DEPARTUREAIRPORT_START',
    FETCH_DEPARTUREAIRPORT_SUCCESS = 'FETCH_DEPARTUREAIRPORT_SUCCESS',
    FETCH_DEPARTUREAIRPORT_FAIL = 'FETCH_DEPARTUREAIRPORT_FAIL'
}